export const ActionTypes = {
    
    'GENERAL_SET_COUNTRY'       :   'GENERAL_SET_COUNTRY',
    'GENERAL_SET_OS'            :   'GENERAL_SET_OS',
    'GENERAL_SET_TRANSLATOR'    :   'GENERAL_SET_TRANSLATOR',
    'GENERAL_SET_HEADER_HEIGHT' :   'GENERAL_SET_HEADER_HEIGHT',
    'PORTAL_SET_FAQ_FILTER'     :   'PORTAL_SET_FAQ_FILTER'
}