export const Images = {
    "clip": require('./../../img/attache-clip.svg'),
    "emoji": require('./../../img/ic-emoticon-smile.svg'),
    "mic": require('./../../img/ic-microphone-a.svg'),
    "plus":require('./../../img/plus-b.svg'),
    "in_tail":require('./../../img/in-tail.svg'),
    "out_tail":require('./../../img/out-tail.svg'),
    "green_tail":require('./../../img/green-tail.png'),
    "white_tail":require('./../../img/white-tail.png'),
    "chat_background": require('./../../img/background-pattern.svg'),
    "add": require('./../../img/add.png'),
    "ok_icon": require('./../../img/ok-icon.png'),
    "cancel_icon": require('./../../img/cancel-icon.png'),
    "file_icon":require('./../../img/file-icon.png'),
    "claro_connect_logo": require('./../../img/logo/claro-connect-logo.svg'),
    "dots_menu":require('./../../img/dots-menu.svg'),
    "forward":require('./../../img/forward.svg'),
    "trash":require('./../../img/trash.svg'),
    "trash_red":require('./../../img/trash-red.svg'),
    "dots_main":require('./../../img/dots-menu.svg'),
    "add_icon":require('./../../img/plus-a.png'),
    "status_user_attach_icon":require('./../../img/status-user-attach.png'),
    "search_icon":require('./../../img/search.png'),
    "send_icon":require('./../../img/send.svg'),
    "close_icon":require('./../../img/close-clear-disable.svg'),
    "reply_icon":require('./../../img/reply-message.svg'),
    "mute_a_icon":require('./../../img/mute-a.png'),
    "file_icon_chat":require('./../../img/file.png'),
    "download_icon":require('./../../img/download-icon.svg'),
    'claro_user_icon':require('./../../img/claro-user.svg'),
    'check_mark_check':require('./../../img/check-mark-check.svg'),
    'check_mark_uncheck':require('./../../img/check-mark-uncheck.svg'),
    'play_icon':require('./../../img/play-icon.svg'),
    'pause_icon':require('./../../img/pause-icon.svg'),
}