export const Images = {
    "clip": require('./../../img/attache-clip.svg'),
    "emoji": require('./../../img/ic-emoticon-smile.svg'),
    "mic": require('./../../img/ic-microphone-a.svg'),
    "plus":require('./../../img/plus-b.svg'),
    "in_tail":require('./../../img/in-tail.svg'),
    "out_tail":require('./../../img/out-tail.svg'),
    "green_tail":require('./../../img/green-tail.png'),
    "white_tail":require('./../../img/white-tail.png'),
    "chat_background": require('./../../img/background-pattern.svg'),
    "add": require('./../../img/add.png'),
    "ok_icon": require('./../../img/ok-icon.png'),
    "cancel_icon": require('./../../img/cancel-icon.png'),
    "file_icon":require('./../../img/file-icon.png'),
    "claro_connect_logo": require('./../../img/logo/claro-connect-logo.svg'),
    "dots_menu":require('./../../img/dots-menu.svg'),
    "search_icon":require('./../../img/search.png'),
    "dots_main":require('./../../img/dots-menu.svg'),
    "add_icon":require('./../../img/plus-a.png')
}