export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const FETCH_CONTACT = 'FETCH_CONTACT';
export const CLEAR_CONTACT = 'CLEAR_CONTACT';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_CONVERSATION = 'FETCH_CONVERSATION';
export const ADD_CONVERSATION = 'ADD_CONVERSATION';
export const FETCH_CONTACT_SECTION = 'FETCH_CONTACT_SECTION';
export const UPDATE_FILTER_CONTACT_CONTACT_SECTION = 'UPDATE_FILTER_CONTACT_CONTACT_SECTION';
export const CONTACT_SECTION_UPDATE_FILTER_CONTACTS = 'CONTACT_SECTION_UPDATE_FILTER_CONTACTS';
export const FETCH_RIGHT_SECTION_CONTAINER = 'FETCH_RIGHT_SECTION_CONTAINER';
export const UPDATE_FILTER_CONTACT_RIGHT_SECTION_CONTAINER = 'UPDATE_FILTER_CONTACT_RIGHT_SECTION_CONTAINER';
export const UPDATE_FILTER_CONTACT_SECTION = 'UPDATE_FILTER_CONTACT_SECTION';
export const SEARCH_CONTACTS = 'SEARCH_CONTACTS';
export const FILE_CONTACTS = 'FILE_CONTACTS';
export const UPDATE_GROUPS = 'UPDATE_GROUPS';
export const HIDE_SECTION_RIGHT = 'HIDE_SECTION_RIGHT';
export const SHOW_ALERT_GENERAL = 'SHOW_ALERT_GENERAL';
export const HIDE_ALERT_GENERAL = 'HIDE_ALERT_GENERAL';
export const PAUSE_HIDE_GENERAL_ALERT = 'PAUSE_HIDE_GENERAL_ALERT';
export const DELETE_CONVERSATION = 'DELETE_CONVERSATION';
export const SHOW_SECTION_GROUPS = 'SHOW_SECTION_GROUPS';
export const SHOW_SECTION_RIGHT = 'SHOW_SECTION_RIGHT';
export const UPDATE_LIST_CONTACTS_GROUP = 'UPDATE_LIST_CONTACTS_GROUP';
export const UPDATE_FILTER_CONTACTS_ADD_GROUP = 'UPDATE_FILTER_CONTACTS_ADD_GROUP';
export const UPDATE_PINER_GROUP = 'UPDATE_PINER_GROUP';
export const UPDATE_LIST_CONTACTS_ADD_GROUP = 'UPDATE_LIST_CONTACTS_ADD_GROUP';
export const HIDE_SECTION_GROUPS = 'HIDE_SECTION_GROUPS';
export const FETCH_GROUPS = 'FETCH_GROUPS';
export const RIGHT_SECTION_CONTAINER = 'RIGHT_SECTION_CONTAINER';
export const ADD_GROUP = 'ADD_GROUP';
export const ADD_CONTACT = 'ADD_CONTACT';
export const SHOW_MULTI_SELECT_MESSAGES = 'SHOW_MULTI_SELECT_MESSAGES';
export const CANCEL_MULTI_SELECT = 'CANCEL_MUTI_SELECT';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const SELECT_MESSAGE = 'SELECT_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const ZTE_CLIENTINIT = 'ZTE_CLIENTINIT';
export const ZTE_GETTOKEN = 'ZTE_GETTOKEN';
export const ZTE_LOGOUT = 'ZTE_LOGOUT';
export const ZTE_SENDSINGLETXTMSG = 'ZTE_SENDSINGLETXTMSG';
export const ZTE_SENDSINGLELOCATIONMSG = 'ZTE_SENDSINGLELOCATIONMSG';
export const ZTE_SENDSINGLEFILE = 'ZTE_SENDSINGLEFILE';
export const ZTE_CBPUSHLINKCONNECTED = 'ZTE_CBPUSHLINKCONNECTED';
export const ZTE_CBPUSHLINKDISCONNECTED = 'ZTE_CBPUSHLINKDISCONNECTED';
export const ZTE_CBREGISTERSUCCESS = 'ZTE_CBREGISTERSUCCESS';
export const ZTE_CBREGISTERFAIL = 'ZTE_CBREGISTERFAIL';
export const ZTE_CBREGISTERREFRESHSUCCESS = 'ZTE_CBREGISTERREFRESHSUCCESS';
export const ZTE_CBREGISTERREFRESHFAIL = 'ZTE_CBREGISTERREFRESHFAIL';
export const ZTE_CBTOKENREFRESHSUCCESS = 'ZTE_CBTOKENREFRESHSUCCESS';
export const ZTE_CBTOKENREFRESHFAIL = 'ZTE_CBTOKENREFRESHFAIL';
export const ZTE_CBSINGLEMSGRECV = 'ZTE_CBSINGLEMSGRECV';
export const ZTE_CBSINGLERECVLOCATION = 'ZTE_CBSINGLERECVLOCATION';
export const ZTE_CBSINGLEMULTMSGRECVBASE = 'ZTE_CBSINGLEMULTMSGRECVBASE';
export const ZTE_CBSINGLEMULTMSGSENDRATE = 'ZTE_CBSINGLEMULTMSGSENDRATE';
export const ZTE_CBHTTPDOWNLOADFILERATE = 'ZTE_CBHTTPDOWNLOADFILERATE';
export const ZTE_CBHTTPDOWNLOADFILE = 'ZTE_CBHTTPDOWNLOADFILE';
export const ZTE_CBSINGLERECVREPORT = 'ZTE_CBSINGLERECVREPORT';
export const modalActions = {
    'SHOW_MODAL':'SHOW_MODAL',
    'SET_BUTTONS':'SET_BUTTONS',
    'SET_TITLE':'SET_TITLE',
    'SET_VIEW':'SET_VIEW'
}
export const ActionTypes = {
    'GENERAL_SET_COUNTRY': 'GENERAL_SET_COUNTRY',
    'GENERAL_SET_OS': 'GENERAL_SET_OS',
    'GENERAL_SET_TRANSLATOR': 'GENERAL_SET_TRANSLATOR',
    'GENERAL_SET_HEADER_HEIGHT': 'GENERAL_SET_HEADER_HEIGHT',
    'PORTAL_SET_FAQ_FILTER': 'PORTAL_SET_FAQ_FILTER'
}