export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const FETCH_CONTACT = 'FETCH_CONTACT';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_CONVERSATION = 'FETCH_CONVERSATION';

export const ZTE_CLIENTINIT = 'ZTE_CLIENTINIT';
export const ZTE_GETTOKEN = 'ZTE_GETTOKEN';
export const ZTE_LOGOUT = 'ZTE_LOGOUT';

export const ZTE_SENDSINGLETXTMSG = 'ZTE_SENDSINGLETXTMSG';
export const ZTE_SENDSINGLELOCATIONMSG = 'ZTE_SENDSINGLELOCATIONMSG';
export const ZTE_SENDSINGLEFILE = 'ZTE_SENDSINGLEFILE';

export const ZTE_CBPUSHLINKCONNECTED= 'ZTE_CBPUSHLINKCONNECTED';
export const ZTE_CBPUSHLINKDISCONNECTED= 'ZTE_CBPUSHLINKDISCONNECTED';
export const ZTE_CBREGISTERSUCCESS= 'ZTE_CBREGISTERSUCCESS';
export const ZTE_CBREGISTERFAIL= 'ZTE_CBREGISTERFAIL';
export const ZTE_CBREGISTERREFRESHSUCCESS= 'ZTE_CBREGISTERREFRESHSUCCESS';
export const ZTE_CBREGISTERREFRESHFAIL= 'ZTE_CBREGISTERREFRESHFAIL'; 
export const ZTE_CBTOKENREFRESHSUCCESS= 'ZTE_CBTOKENREFRESHSUCCESS';
export const ZTE_CBTOKENREFRESHFAIL= 'ZTE_CBTOKENREFRESHFAIL';
export const ZTE_CBSINGLEMSGRECV= 'ZTE_CBSINGLEMSGRECV';
export const ZTE_CBSINGLERECVLOCATION= 'ZTE_CBSINGLERECVLOCATION';
export const ZTE_CBSINGLEMULTMSGRECVBASE= 'ZTE_CBSINGLEMULTMSGRECVBASE';
export const ZTE_CBSINGLEMULTMSGSENDRATE= 'ZTE_CBSINGLEMULTMSGSENDRATE';
export const ZTE_CBHTTPDOWNLOADFILERATE= 'ZTE_CBHTTPDOWNLOADFILERATE';
export const ZTE_CBHTTPDOWNLOADFILE= 'ZTE_CBHTTPDOWNLOADFILE';
export const ZTE_CBSINGLERECVREPORT= 'ZTE_CBSINGLERECVREPORT';